package tablas;
// Generated 16/08/2018 17:29:45 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set peliculas = new HashSet(0);

	public Genero() {
	}

	public Genero(String nombre) {
		this.nombre = nombre;
	}

	public Genero(String nombre, Set peliculas) {
		this.nombre = nombre;
		this.peliculas = peliculas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Set peliculas) {
		this.peliculas = peliculas;
	}

}
