package tablas;
// Generated 16/08/2018 17:29:45 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula implements java.io.Serializable {

	private Integer id;
	private Genero genero;
	private String titulo;
	private int duracion;
	private String director;
	private int anio;
	private Date fechaLanzamiento;
	private Integer puntuacion;
	private String poster;
	private String trama;
	private Set actorPeliculas = new HashSet(0);

	public Pelicula() {
	}

	public Pelicula(String titulo, int duracion, String director, int anio, Date fechaLanzamiento) {
		this.titulo = titulo;
		this.duracion = duracion;
		this.director = director;
		this.anio = anio;
		this.fechaLanzamiento = fechaLanzamiento;
	}

	public Pelicula(Genero genero, String titulo, int duracion, String director, int anio, Date fechaLanzamiento,
			Integer puntuacion, String poster, String trama, Set actorPeliculas) {
		this.genero = genero;
		this.titulo = titulo;
		this.duracion = duracion;
		this.director = director;
		this.anio = anio;
		this.fechaLanzamiento = fechaLanzamiento;
		this.puntuacion = puntuacion;
		this.poster = poster;
		this.trama = trama;
		this.actorPeliculas = actorPeliculas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public Date getFechaLanzamiento() {
		return this.fechaLanzamiento;
	}

	public void setFechaLanzamiento(Date fechaLanzamiento) {
		this.fechaLanzamiento = fechaLanzamiento;
	}

	public Integer getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(Integer puntuacion) {
		this.puntuacion = puntuacion;
	}

	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	public String getTrama() {
		return this.trama;
	}

	public void setTrama(String trama) {
		this.trama = trama;
	}

	public Set getActorPeliculas() {
		return this.actorPeliculas;
	}

	public void setActorPeliculas(Set actorPeliculas) {
		this.actorPeliculas = actorPeliculas;
	}

}
